name: "JK-BMS Modbus RS485"
description: "Surveillance de JK-BMS type JK_PB2A16S15P via Modbus RS485 By Smartphoton"
version: "1.0.0"
slug: "jk-bms_modbus_rs485"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
uart: true
ports:
  1880/tcp: 1888
ports_description:
  1888/tcp: "Interface Web Node-RED"
devices:
  - /dev/ttyUSB0
  - /dev/ttyAMA0
options:
  device: "/dev/ttyUSB0"
  baud_rate: 115200
  data_bits: 8
  parity: "N"
  stop_bits: 1
schema:
  device: "str"
  baud_rate: "int"
  data_bits: "int"
  parity: "str"
  stop_bits: "int"
